# Generated by Django 3.0.7 on 2020-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200806_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='i',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
