# Generated by Django 3.0.7 on 2020-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
